config/routes.rb
Rails.application.routes.draw do
  resources :shorteners, except: :show
	get ':short_url', to: 'shorteners#redirect', as: :short
	get ':short_url/stats', to: 'shorteners#stats', as: :stats
  root "shorteners#index"
end

app/models/shortener.rb
class Shortener < ActiveRecord::Base
	before_validation :set_value
  has_many :shortener_details
  validates :short_url, :destination_url, :own_ip, presence: true
  validates :short_url, uniqueness: true
	scope :list, lambda { where(own_ip: self.ip) }

	def self.ip
	  orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true
	  UDPSocket.open do |soket|
	    soket.connect '64.233.187.99', 1
	    soket.addr.last
	  end
		ensure
	  Socket.do_not_reverse_lookup = orig
	end

	protected
		def set_value
			self.own_ip = self.class.ip
		  unless self.destination_url[/\Ahttp:\/\//] || self.destination_url[/\Ahttps:\/\//]
		    self.destination_url = "http://#{self.destination_url}"
		  end
		  self.short_url = self.short_url.gsub(/\Ahttp:\/\/|\Ahttps:\/\//, "")
		end
end

app/models/shortener_detail.rb
class ShortenerDetail < ActiveRecord::Base
	belongs_to :shortener

	def self.recording(shortener, request)
		useragent = UserAgent.parse(request.env['HTTP_USER_AGENT'])
		self.create({
			shortener_id: shortener.id,
			ip: Shortener.ip,
			os: os(request.env['HTTP_USER_AGENT']),
			browser: "#{useragent.browser} #{useragent.version} "
		})
	end

	protected
		def self.os(request)
			case request.downcase
				when /mac/i
			    "Mac"
			  when /windows/i
			    "Windows"
			  when /linux/i
			    "Linux"
			  when /unix/i
			    "Unix"
			  else
			    "Unknown"
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  before_action :shorteners
  before_action :set_shortener, only: [:edit, :update, :destroy, :redirect, :stats]
  before_action :set_new_shortener, only: [:index, :create]

  def create
    if @shortener.save
      set_new_shortener(nil)
    end
  end

  def update
    if @shortener.update(shortener_params)
      set_new_shortener(nil)
    end
  end

  def destroy
    if @shortener.destroy
      set_new_shortener(nil)
    end
  end

  def redirect
    ShortenerDetail.recording(@shortener, request)
    redirect_to @shortener.destination_url
  end

  def stats
    respond_to do |format|
      format.html
      format.json  { render file: "/shorteners/stats.json.erb", content_type: 'application/json' }
    end
  end

  private
    def shorteners
      @shorteners = Shortener.list
    end

    def set_shortener
      @shortener = Shortener.find(params[:id]) rescue Shortener.find_by_short_url(params[:short_url])
    end

    def set_new_shortener(_shortener_params = shortener_params)
      @shortener = Shortener.new(_shortener_params)
    end

    def shortener_params
      params.require(:shortener).permit(:short_url, :destination_url, :own_ip) if params[:shortener]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_destination(data)
		link_to data.destination_url.gsub(/\Ahttp:\/\/|\Ahttps:\/\//, ""), data.destination_url, target: "_blank"
	end

	def link_short(data)
		link_to "#{request.host_with_port}/#{data.short_url}", short_path(data.short_url), target: "_blank"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shorteners/create.js.erb
<%= render "shorteners/shared/refresh" %>

app/views/shorteners/destroy.js.erb
<%= render "shorteners/shared/refresh" %>

app/views/shorteners/edit.js.erb
$("#form").html("<%= j render 'shorteners/shared/form' %>");

app/views/shorteners/index.html.erb
<div id="parent">
	<div id="form">
		<%= render "shorteners/shared/form" %>
	</div>
	<br/><br/><br/><br/>
	<div id="list">
		<%= render "shorteners/shared/list" %>
	</div>
</div>

app/views/shorteners/shared/_form.html.erb
<%= form_for @shortener, remote: true do |f| %>
  <div class="group">
	  <%= f.text_field :destination_url,placeholder: "Destination URL" %>
	  <span class="error_message">
	  	<%= f.object.errors[:destination_url].join(" and ") rescue "" %>
	  </span>
  </div>
  <div class="group">
	  <%= f.text_field :short_url,placeholder: "Short URL" %>
	  <span class="error_message">
	  	<%= f.object.errors[:short_url].join(" and ") rescue "" %>
	  </span>
  </div>
  <div class="group">
  	<%= f.submit %>
  </div>
<% end %>

app/views/shorteners/shared/_list.html.erb
<table>
  <thead>
    <tr>
      <th width="5%">No</th>
      <th>Destination URL</th>
      <th>Short URL</th>
      <th>Clicks</th>
      <th width="22%">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @shorteners.each_with_index do |shortener, i| %>
      <tr>
        <td class="center"><%= i+1 %></td>
        <td><%= link_destination(shortener) %></td>
        <td><%= link_short(shortener) %></td>
        <td class="center"><%= shortener.shortener_details.size %></td>
        <td class="center">
          <%= link_to 'Edit', edit_shortener_path(shortener), remote: true %> | 
          <%=
            link_to 'Delete', shortener, method: :delete,
            data: { confirm: "are you sure?"}, remote: true
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shorteners/shared/_refresh.js.erb
<% if @shortener.errors.present? %>
	$("#form").html("<%= j render 'shorteners/shared/form' %>");
<% else %>
	$("#form").html("<%= j render 'shorteners/shared/form' %>");
	$("#list").html("<%= j render 'shorteners/shared/list' %>");
<% end %>

app/views/shorteners/stats.json.erb
{
  destination_url: <%= @shortener.destination_url %>,
  short_url: <%= @shortener.short_url %>,
  shortener: <%= @shortener.shortener_details.select("id, ip, os, browser").to_json.html_safe %>,
  clicks: <%= @shortener.shortener_details.size %>
}

app/views/shorteners/update.js.erb
<%= render "shorteners/shared/refresh" %>